using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("OctopusProjectBuilder.YamlReader")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("OctopusProjectBuilder.YamlReader")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("a523e71b-b139-425d-b810-21fc17c8f7bd")]
